# The Docker image to run your workspace in.
image: gitpod/workspace-full

# Command to start on workspace startup
tasks:
  - init: |
      npm install -g @angular/cli ajv-cli ajv-formats
      yarn
      ng analytics off
    command: ng serve
# Ports to expose on workspace startup
ports:
  - port: 4200
    onOpen: open-preview
vscode:
  extensions:
    - angular.ng-template