version: '2.4'
services:
  mobilespectrum:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 4200:4200
    volumes:
    - .:/usr/src/app
    - mobilespectrum_node_modules:/usr/src/app/node_modules

volumes:
  mobilespectrum_node_modules: